# Generated by Django 2.0.6 on 2018-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_auto_20180616_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, help_text='Do not edit field manually', max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text='Do not edit field manually', max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, help_text='Do not edit field manually', max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
